spring.application.name=PixelWars

spring.profiles.active=secrets
spring.config.import=file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/pixelwars
spring.datasource.username=${postgresql.username}
spring.datasource.password=${postgresql.password}

spring.security.oauth2.client.registration.google.client-id=${OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_CLIENT_SECRET}

server.address=0.0.0.0
server.port=80
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-response=true
